version: "3.9"

services:
  avolicius-app:
    image: ghcr.io/yerry888/sistem-informasi-manajemen-pemesanan-produk-berbasis-alpukat-avolicius-be:v1.0.0

    container_name: avolicius-app

    restart: unless-stopped

    ports:
      - "8080:80"

    env_file:
      - .env

    volumes:
      # Bind Mount Source Code
      - ./:/var/www/html

      # Bind Mount Images
      - ./assets/images:/var/www/html/assets/images

      # Bind Mount Logs
      - ./logs:/var/www/html/logs

    depends_on:
      - mysql

    networks:
      - avolicius-network

  mysql:
    image: mysql:8.0

    container_name: avolicius-db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: avolicius_db

    ports:
      - "3306:3306"

    volumes:
      # Named Volume
      - mysql-data:/var/lib/mysql

    networks:
      - avolicius-network

volumes:
  mysql-data:

networks:
  avolicius-network:
    driver: bridge
